name: Second action

on:
  # Manual trigger from the UI
  workflow_dispatch:

  # Dependency to a forking workflow
  workflow_run:
    workflows: ["First action"]
    type:
      - complete


jobs:
  say_hi_again:
    runs-on: ubuntu-latest
    steps:
      - name: Hi again
        run: echo "Hi from the second action"
